export class RefrigeratorActions {
    static FETCH_REFRIGERATORS = 'FETCH_REFRIGERATORS';
    static FETCH_REFRIGERATORS_SUCCESS = 'FETCH_REFRIGERATORS_SUCCESS';
    static FETCH_REFRIGERATORS_ERROR = 'FETCH_REFRIGERATORS_ERROR';
    static ADD_REFRIGERATOR = 'ADD_REFRIGERATOR';
    static ADD_REFRIGERATOR_SUCCESS = 'ADD_REFRIGERATOR_SUCCESS';
    static ADD_REFRIGERATOR_ERROR = 'ADD_REFRIGERATOR_ERROR';
}
export class RefrigeratorAction {
    type: RefrigeratorActions;
    payload?: any;
}
